// Code generated by goctl. DO NOT EDIT.
// Source: rpc_demo.proto

package server

import (
	"context"

	"rpc_demo/internal/logic/rpc_demo"
	"rpc_demo/internal/svc"
	"rpc_demo/rpc"
)

type RpcDemoServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedRpcDemoServer
}

func NewRpcDemoServer(svcCtx *svc.ServiceContext) *RpcDemoServer {
	return &RpcDemoServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcDemoServer) Ping(ctx context.Context, in *rpc.Request) (*rpc.Response, error) {
	l := rpcdemologic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *RpcDemoServer) FindOne(ctx context.Context, in *rpc.GameInfoReq) (*rpc.GameInfoRep, error) {
	l := rpcdemologic.NewFindOneLogic(ctx, s.svcCtx)
	return l.FindOne(in)
}

func (s *RpcDemoServer) GameList(ctx context.Context, in *rpc.GameListReq) (*rpc.GameListRep, error) {
	l := rpcdemologic.NewGameListLogic(ctx, s.svcCtx)
	return l.GameList(in)
}
