// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	demo "api_demo/internal/handler/demo"
	"api_demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: demo.Api_demoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/find_id",
				Handler: demo.FindByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/list",
				Handler: demo.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/list_export",
				Handler: demo.List_exportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/demo"),
	)
}
