// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: dsl/demo_service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOrder int32

const (
	SortOrder_ASC  SortOrder = 0
	SortOrder_DESC SortOrder = 1
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortOrder_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_dsl_demo_service_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_dsl_demo_service_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{0}
}

type SearchOperator int32

const (
	SearchOperator_EQ       SearchOperator = 0  // 等于
	SearchOperator_NE       SearchOperator = 1  // 不等于
	SearchOperator_GT       SearchOperator = 2  // 大于
	SearchOperator_GE       SearchOperator = 3  // 大于等于
	SearchOperator_LT       SearchOperator = 4  // 小于
	SearchOperator_LE       SearchOperator = 5  // 小于等于
	SearchOperator_LIKE     SearchOperator = 6  // 使用like的模糊匹配
	SearchOperator_WILDCARD SearchOperator = 7  // 使用通配符的模糊匹配
	SearchOperator_IN       SearchOperator = 8  // 在指定的集合中
	SearchOperator_NOT_IN   SearchOperator = 9  // 不在指定的集合中
	SearchOperator_BETWEEN  SearchOperator = 10 // 在指定的范围内
	SearchOperator_RE       SearchOperator = 11 // 正则匹配
)

// Enum value maps for SearchOperator.
var (
	SearchOperator_name = map[int32]string{
		0:  "EQ",
		1:  "NE",
		2:  "GT",
		3:  "GE",
		4:  "LT",
		5:  "LE",
		6:  "LIKE",
		7:  "WILDCARD",
		8:  "IN",
		9:  "NOT_IN",
		10: "BETWEEN",
		11: "RE",
	}
	SearchOperator_value = map[string]int32{
		"EQ":       0,
		"NE":       1,
		"GT":       2,
		"GE":       3,
		"LT":       4,
		"LE":       5,
		"LIKE":     6,
		"WILDCARD": 7,
		"IN":       8,
		"NOT_IN":   9,
		"BETWEEN":  10,
		"RE":       11,
	}
)

func (x SearchOperator) Enum() *SearchOperator {
	p := new(SearchOperator)
	*p = x
	return p
}

func (x SearchOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_dsl_demo_service_proto_enumTypes[1].Descriptor()
}

func (SearchOperator) Type() protoreflect.EnumType {
	return &file_dsl_demo_service_proto_enumTypes[1]
}

func (x SearchOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchOperator.Descriptor instead.
func (SearchOperator) EnumDescriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{1}
}

type FileContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 所属业务领域，用于创建bucket
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// 所属业务名称
	BizName string `protobuf:"bytes,2,opt,name=biz_name,json=bizName,proto3" json:"biz_name,omitempty"`
	FileId  int64  `protobuf:"varint,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// 文件md5
	Hash string `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	// 文件类型
	FileType string `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	// 文件大小，单位byte
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	// 文件访问链接的过期时间
	ExpireSeconds int64 `protobuf:"varint,7,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds,omitempty"`
	// 文件名
	Filename      string `protobuf:"bytes,8,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContext) Reset() {
	*x = FileContext{}
	mi := &file_dsl_demo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContext) ProtoMessage() {}

func (x *FileContext) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContext.ProtoReflect.Descriptor instead.
func (*FileContext) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileContext) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *FileContext) GetBizName() string {
	if x != nil {
		return x.BizName
	}
	return ""
}

func (x *FileContext) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *FileContext) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileContext) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *FileContext) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileContext) GetExpireSeconds() int64 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

func (x *FileContext) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type PreSignGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContext   *FileContext           `protobuf:"bytes,1,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignGetRequest) Reset() {
	*x = PreSignGetRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignGetRequest) ProtoMessage() {}

func (x *PreSignGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignGetRequest.ProtoReflect.Descriptor instead.
func (*PreSignGetRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{1}
}

func (x *PreSignGetRequest) GetFileContext() *FileContext {
	if x != nil {
		return x.FileContext
	}
	return nil
}

type PreSignGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignGetResponse) Reset() {
	*x = PreSignGetResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignGetResponse) ProtoMessage() {}

func (x *PreSignGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignGetResponse.ProtoReflect.Descriptor instead.
func (*PreSignGetResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{2}
}

func (x *PreSignGetResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PreSignGetResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PreSignPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContext   *FileContext           `protobuf:"bytes,1,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignPutRequest) Reset() {
	*x = PreSignPutRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignPutRequest) ProtoMessage() {}

func (x *PreSignPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignPutRequest.ProtoReflect.Descriptor instead.
func (*PreSignPutRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{3}
}

func (x *PreSignPutRequest) GetFileContext() *FileContext {
	if x != nil {
		return x.FileContext
	}
	return nil
}

type PreSignPutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Url   string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// file_id will be not null if the put request file hash has been uploaded
	FileId        int64 `protobuf:"varint,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignPutResponse) Reset() {
	*x = PreSignPutResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignPutResponse) ProtoMessage() {}

func (x *PreSignPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignPutResponse.ProtoReflect.Descriptor instead.
func (*PreSignPutResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{4}
}

func (x *PreSignPutResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PreSignPutResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PreSignPutResponse) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type ReportUploadedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContext   *FileContext           `protobuf:"bytes,1,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUploadedRequest) Reset() {
	*x = ReportUploadedRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUploadedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUploadedRequest) ProtoMessage() {}

func (x *ReportUploadedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUploadedRequest.ProtoReflect.Descriptor instead.
func (*ReportUploadedRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReportUploadedRequest) GetFileContext() *FileContext {
	if x != nil {
		return x.FileContext
	}
	return nil
}

type ReportUploadedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUploadedResponse) Reset() {
	*x = ReportUploadedResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUploadedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUploadedResponse) ProtoMessage() {}

func (x *ReportUploadedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUploadedResponse.ProtoReflect.Descriptor instead.
func (*ReportUploadedResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReportUploadedResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReportUploadedResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PreSignSlicingPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContext   *FileContext           `protobuf:"bytes,1,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignSlicingPutRequest) Reset() {
	*x = PreSignSlicingPutRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignSlicingPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignSlicingPutRequest) ProtoMessage() {}

func (x *PreSignSlicingPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignSlicingPutRequest.ProtoReflect.Descriptor instead.
func (*PreSignSlicingPutRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{7}
}

func (x *PreSignSlicingPutRequest) GetFileContext() *FileContext {
	if x != nil {
		return x.FileContext
	}
	return nil
}

type PreSignSlicingPutResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Meta     *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Urls     []string               `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	UploadId string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Parts    int64                  `protobuf:"varint,4,opt,name=parts,proto3" json:"parts,omitempty"`
	FileId   int64                  `protobuf:"varint,5,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// if a file has been uploaded, this field will be true
	Uploaded      bool `protobuf:"varint,6,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignSlicingPutResponse) Reset() {
	*x = PreSignSlicingPutResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignSlicingPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignSlicingPutResponse) ProtoMessage() {}

func (x *PreSignSlicingPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignSlicingPutResponse.ProtoReflect.Descriptor instead.
func (*PreSignSlicingPutResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{8}
}

func (x *PreSignSlicingPutResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PreSignSlicingPutResponse) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *PreSignSlicingPutResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *PreSignSlicingPutResponse) GetParts() int64 {
	if x != nil {
		return x.Parts
	}
	return 0
}

func (x *PreSignSlicingPutResponse) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *PreSignSlicingPutResponse) GetUploaded() bool {
	if x != nil {
		return x.Uploaded
	}
	return false
}

type GetProgressRate4SlicingPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContext   *FileContext           `protobuf:"bytes,1,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRate4SlicingPutRequest) Reset() {
	*x = GetProgressRate4SlicingPutRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRate4SlicingPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRate4SlicingPutRequest) ProtoMessage() {}

func (x *GetProgressRate4SlicingPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRate4SlicingPutRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRate4SlicingPutRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetProgressRate4SlicingPutRequest) GetFileContext() *FileContext {
	if x != nil {
		return x.FileContext
	}
	return nil
}

func (x *GetProgressRate4SlicingPutRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type GetProgressRate4SlicingPutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Meta  *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// 进度百分比
	ProgressRate float32 `protobuf:"fixed32,2,opt,name=progress_rate,json=progressRate,proto3" json:"progress_rate,omitempty"`
	// 分片上传情况
	Parts         map[string]bool `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRate4SlicingPutResponse) Reset() {
	*x = GetProgressRate4SlicingPutResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRate4SlicingPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRate4SlicingPutResponse) ProtoMessage() {}

func (x *GetProgressRate4SlicingPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRate4SlicingPutResponse.ProtoReflect.Descriptor instead.
func (*GetProgressRate4SlicingPutResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetProgressRate4SlicingPutResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetProgressRate4SlicingPutResponse) GetProgressRate() float32 {
	if x != nil {
		return x.ProgressRate
	}
	return 0
}

func (x *GetProgressRate4SlicingPutResponse) GetParts() map[string]bool {
	if x != nil {
		return x.Parts
	}
	return nil
}

type ReportUploadedFilePartsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	FileId        int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	PartNumber    int64                  `protobuf:"varint,3,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUploadedFilePartsRequest) Reset() {
	*x = ReportUploadedFilePartsRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUploadedFilePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUploadedFilePartsRequest) ProtoMessage() {}

func (x *ReportUploadedFilePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUploadedFilePartsRequest.ProtoReflect.Descriptor instead.
func (*ReportUploadedFilePartsRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReportUploadedFilePartsRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ReportUploadedFilePartsRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *ReportUploadedFilePartsRequest) GetPartNumber() int64 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

type ReportUploadedFilePartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUploadedFilePartsResponse) Reset() {
	*x = ReportUploadedFilePartsResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUploadedFilePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUploadedFilePartsResponse) ProtoMessage() {}

func (x *ReportUploadedFilePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUploadedFilePartsResponse.ProtoReflect.Descriptor instead.
func (*ReportUploadedFilePartsResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReportUploadedFilePartsResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type MergeFilePartsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContext   *FileContext           `protobuf:"bytes,1,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"`
	UploadId      string                 `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeFilePartsRequest) Reset() {
	*x = MergeFilePartsRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeFilePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeFilePartsRequest) ProtoMessage() {}

func (x *MergeFilePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeFilePartsRequest.ProtoReflect.Descriptor instead.
func (*MergeFilePartsRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{13}
}

func (x *MergeFilePartsRequest) GetFileContext() *FileContext {
	if x != nil {
		return x.FileContext
	}
	return nil
}

func (x *MergeFilePartsRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type MergeFilePartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeFilePartsResponse) Reset() {
	*x = MergeFilePartsResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeFilePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeFilePartsResponse) ProtoMessage() {}

func (x *MergeFilePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeFilePartsResponse.ProtoReflect.Descriptor instead.
func (*MergeFilePartsResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{14}
}

func (x *MergeFilePartsResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RemoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContext   *FileContext           `protobuf:"bytes,1,opt,name=file_context,json=fileContext,proto3" json:"file_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileRequest) Reset() {
	*x = RemoveFileRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileRequest) ProtoMessage() {}

func (x *RemoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveFileRequest) GetFileContext() *FileContext {
	if x != nil {
		return x.FileContext
	}
	return nil
}

type RemoveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileResponse) Reset() {
	*x = RemoveFileResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileResponse) ProtoMessage() {}

func (x *RemoveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveFileResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetFileInfoByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        int64                  `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	DomainName    string                 `protobuf:"bytes,2,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	BizName       string                 `protobuf:"bytes,3,opt,name=biz_name,json=bizName,proto3" json:"biz_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoByIdRequest) Reset() {
	*x = GetFileInfoByIdRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoByIdRequest) ProtoMessage() {}

func (x *GetFileInfoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoByIdRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoByIdRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetFileInfoByIdRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *GetFileInfoByIdRequest) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *GetFileInfoByIdRequest) GetBizName() string {
	if x != nil {
		return x.BizName
	}
	return ""
}

type GetFileInfoByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ObjectName    string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoByIdResponse) Reset() {
	*x = GetFileInfoByIdResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoByIdResponse) ProtoMessage() {}

func (x *GetFileInfoByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoByIdResponse.ProtoReflect.Descriptor instead.
func (*GetFileInfoByIdResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetFileInfoByIdResponse) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetFileInfoByIdResponse) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *GetFileInfoByIdResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizCode       int32                  `protobuf:"varint,1,opt,name=biz_code,json=bizCode,proto3" json:"biz_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Reason        []string               `protobuf:"bytes,4,rep,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_dsl_demo_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{19}
}

func (x *Metadata) GetBizCode() int32 {
	if x != nil {
		return x.BizCode
	}
	return 0
}

func (x *Metadata) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Metadata) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Metadata) GetReason() []string {
	if x != nil {
		return x.Reason
	}
	return nil
}

type SortField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                     // 用于排序的字段名称
	Order         SortOrder              `protobuf:"varint,2,opt,name=order,proto3,enum=rpc.SortOrder" json:"order,omitempty"` // 排序方式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortField) Reset() {
	*x = SortField{}
	mi := &file_dsl_demo_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortField) ProtoMessage() {}

func (x *SortField) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortField.ProtoReflect.Descriptor instead.
func (*SortField) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{20}
}

func (x *SortField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortField) GetOrder() SortOrder {
	if x != nil {
		return x.Order
	}
	return SortOrder_ASC
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 页码 [1, +∞)
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 页面大小
	Sort          []*SortField           `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`  // 根据字段进行排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{21}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PaginationRequest) GetSort() []*SortField {
	if x != nil {
		return x.Sort
	}
	return nil
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // 当前数据的所属页码
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总页数
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // 总条目数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_dsl_demo_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{22}
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`                                // 用于搜索的字段名称
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                // 搜索的值
	ValueList     []string               `protobuf:"bytes,3,rep,name=value_list,json=valueList,proto3" json:"value_list,omitempty"`       // 搜索的值列表
	Operator      SearchOperator         `protobuf:"varint,4,opt,name=operator,proto3,enum=rpc.SearchOperator" json:"operator,omitempty"` // 操作符
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchField) Reset() {
	*x = SearchField{}
	mi := &file_dsl_demo_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchField) ProtoMessage() {}

func (x *SearchField) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchField.ProtoReflect.Descriptor instead.
func (*SearchField) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{23}
}

func (x *SearchField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SearchField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SearchField) GetValueList() []string {
	if x != nil {
		return x.ValueList
	}
	return nil
}

func (x *SearchField) GetOperator() SearchOperator {
	if x != nil {
		return x.Operator
	}
	return SearchOperator_EQ
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        []*SearchField         `protobuf:"bytes,1,rep,name=search,proto3" json:"search,omitempty"` // 搜索条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_dsl_demo_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{24}
}

func (x *SearchRequest) GetSearch() []*SearchField {
	if x != nil {
		return x.Search
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_dsl_demo_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{25}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_dsl_demo_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{26}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type GameInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfoReq) Reset() {
	*x = GameInfoReq{}
	mi := &file_dsl_demo_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoReq) ProtoMessage() {}

func (x *GameInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoReq.ProtoReflect.Descriptor instead.
func (*GameInfoReq) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{27}
}

func (x *GameInfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreateTime    string                 `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	mi := &file_dsl_demo_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{28}
}

func (x *GameInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GameInfo) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GameInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *GameInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type GameInfoRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *GameInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfoRep) Reset() {
	*x = GameInfoRep{}
	mi := &file_dsl_demo_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfoRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoRep) ProtoMessage() {}

func (x *GameInfoRep) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoRep.ProtoReflect.Descriptor instead.
func (*GameInfoRep) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{29}
}

func (x *GameInfoRep) GetInfo() *GameInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GameListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameListReq) Reset() {
	*x = GameListReq{}
	mi := &file_dsl_demo_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameListReq) ProtoMessage() {}

func (x *GameListReq) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameListReq.ProtoReflect.Descriptor instead.
func (*GameListReq) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{30}
}

func (x *GameListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GameListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GameListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GameInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameListRep) Reset() {
	*x = GameListRep{}
	mi := &file_dsl_demo_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameListRep) ProtoMessage() {}

func (x *GameListRep) ProtoReflect() protoreflect.Message {
	mi := &file_dsl_demo_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameListRep.ProtoReflect.Descriptor instead.
func (*GameListRep) Descriptor() ([]byte, []int) {
	return file_dsl_demo_service_proto_rawDescGZIP(), []int{31}
}

func (x *GameListRep) GetList() []*GameInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_dsl_demo_service_proto protoreflect.FileDescriptor

const file_dsl_demo_service_proto_rawDesc = "" +
	"\n" +
	"\x16dsl/demo_service.proto\x12\x03rpc\"\xe1\x01\n" +
	"\vFileContext\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x19\n" +
	"\bbiz_name\x18\x02 \x01(\tR\abizName\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\x03R\x06fileId\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12%\n" +
	"\x0eexpire_seconds\x18\a \x01(\x03R\rexpireSeconds\x12\x1a\n" +
	"\bfilename\x18\b \x01(\tR\bfilename\"H\n" +
	"\x11PreSignGetRequest\x123\n" +
	"\ffile_context\x18\x01 \x01(\v2\x10.rpc.FileContextR\vfileContext\"I\n" +
	"\x12PreSignGetResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"H\n" +
	"\x11PreSignPutRequest\x123\n" +
	"\ffile_context\x18\x01 \x01(\v2\x10.rpc.FileContextR\vfileContext\"b\n" +
	"\x12PreSignPutResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\x03R\x06fileId\"L\n" +
	"\x15ReportUploadedRequest\x123\n" +
	"\ffile_context\x18\x01 \x01(\v2\x10.rpc.FileContextR\vfileContext\"M\n" +
	"\x16ReportUploadedResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"O\n" +
	"\x18PreSignSlicingPutRequest\x123\n" +
	"\ffile_context\x18\x01 \x01(\v2\x10.rpc.FileContextR\vfileContext\"\xba\x01\n" +
	"\x19PreSignSlicingPutResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12\x14\n" +
	"\x05parts\x18\x04 \x01(\x03R\x05parts\x12\x17\n" +
	"\afile_id\x18\x05 \x01(\x03R\x06fileId\x12\x1a\n" +
	"\buploaded\x18\x06 \x01(\bR\buploaded\"u\n" +
	"!GetProgressRate4SlicingPutRequest\x123\n" +
	"\ffile_context\x18\x01 \x01(\v2\x10.rpc.FileContextR\vfileContext\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\"\xf0\x01\n" +
	"\"GetProgressRate4SlicingPutResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\x12#\n" +
	"\rprogress_rate\x18\x02 \x01(\x02R\fprogressRate\x12H\n" +
	"\x05parts\x18\x03 \x03(\v22.rpc.GetProgressRate4SlicingPutResponse.PartsEntryR\x05parts\x1a8\n" +
	"\n" +
	"PartsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"w\n" +
	"\x1eReportUploadedFilePartsRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\x12\x1f\n" +
	"\vpart_number\x18\x03 \x01(\x03R\n" +
	"partNumber\"D\n" +
	"\x1fReportUploadedFilePartsResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\"i\n" +
	"\x15MergeFilePartsRequest\x123\n" +
	"\ffile_context\x18\x01 \x01(\v2\x10.rpc.FileContextR\vfileContext\x12\x1b\n" +
	"\tupload_id\x18\x02 \x01(\tR\buploadId\";\n" +
	"\x16MergeFilePartsResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\"H\n" +
	"\x11RemoveFileRequest\x123\n" +
	"\ffile_context\x18\x01 \x01(\v2\x10.rpc.FileContextR\vfileContext\"7\n" +
	"\x12RemoveFileResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\"m\n" +
	"\x16GetFileInfoByIdRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x03R\x06fileId\x12\x1f\n" +
	"\vdomain_name\x18\x02 \x01(\tR\n" +
	"domainName\x12\x19\n" +
	"\bbiz_name\x18\x03 \x01(\tR\abizName\"q\n" +
	"\x17GetFileInfoByIdResponse\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.rpc.MetadataR\x04meta\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"o\n" +
	"\bMetadata\x12\x19\n" +
	"\bbiz_code\x18\x01 \x01(\x05R\abizCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06reason\x18\x04 \x03(\tR\x06reason\"G\n" +
	"\tSortField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12$\n" +
	"\x05order\x18\x02 \x01(\x0e2\x0e.rpc.SortOrderR\x05order\"_\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\"\n" +
	"\x04sort\x18\x03 \x03(\v2\x0e.rpc.SortFieldR\x04sort\"T\n" +
	"\x12PaginationResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x89\x01\n" +
	"\vSearchField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"value_list\x18\x03 \x03(\tR\tvalueList\x12/\n" +
	"\boperator\x18\x04 \x01(\x0e2\x13.rpc.SearchOperatorR\boperator\"9\n" +
	"\rSearchRequest\x12(\n" +
	"\x06search\x18\x01 \x03(\v2\x10.rpc.SearchFieldR\x06search\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"\x1d\n" +
	"\vGameInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x98\x01\n" +
	"\bGameInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x06 \x01(\tR\n" +
	"updateTime\"0\n" +
	"\vGameInfoRep\x12!\n" +
	"\x04info\x18\x01 \x01(\v2\r.rpc.GameInfoR\x04info\"=\n" +
	"\vGameListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"0\n" +
	"\vGameListRep\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.rpc.GameInfoR\x04list*\x1e\n" +
	"\tSortOrder\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x01*\x81\x01\n" +
	"\x0eSearchOperator\x12\x06\n" +
	"\x02EQ\x10\x00\x12\x06\n" +
	"\x02NE\x10\x01\x12\x06\n" +
	"\x02GT\x10\x02\x12\x06\n" +
	"\x02GE\x10\x03\x12\x06\n" +
	"\x02LT\x10\x04\x12\x06\n" +
	"\x02LE\x10\x05\x12\b\n" +
	"\x04LIKE\x10\x06\x12\f\n" +
	"\bWILDCARD\x10\a\x12\x06\n" +
	"\x02IN\x10\b\x12\n" +
	"\n" +
	"\x06NOT_IN\x10\t\x12\v\n" +
	"\aBETWEEN\x10\n" +
	"\x12\x06\n" +
	"\x02RE\x10\v2\xf1\x04\n" +
	"\vFileService\x12=\n" +
	"\n" +
	"PreSignGet\x12\x16.rpc.PreSignGetRequest\x1a\x17.rpc.PreSignGetResponse\x12=\n" +
	"\n" +
	"PreSignPut\x12\x16.rpc.PreSignPutRequest\x1a\x17.rpc.PreSignPutResponse\x12I\n" +
	"\x0eReportUploaded\x12\x1a.rpc.ReportUploadedRequest\x1a\x1b.rpc.ReportUploadedResponse\x12R\n" +
	"\x11PreSignSlicingPut\x12\x1d.rpc.PreSignSlicingPutRequest\x1a\x1e.rpc.PreSignSlicingPutResponse\x12m\n" +
	"\x1aGetProgressRate4SlicingPut\x12&.rpc.GetProgressRate4SlicingPutRequest\x1a'.rpc.GetProgressRate4SlicingPutResponse\x12I\n" +
	"\x0eMergeFileParts\x12\x1a.rpc.MergeFilePartsRequest\x1a\x1b.rpc.MergeFilePartsResponse\x12=\n" +
	"\n" +
	"RemoveFile\x12\x16.rpc.RemoveFileRequest\x1a\x17.rpc.RemoveFileResponse\x12L\n" +
	"\x0fGetFileInfoById\x12\x1b.rpc.GetFileInfoByIdRequest\x1a\x1c.rpc.GetFileInfoByIdResponse2\xc3\x01\n" +
	"\bRpc_demo\x12#\n" +
	"\x04Ping\x12\f.rpc.Request\x1a\r.rpc.Response\x12-\n" +
	"\aFindOne\x12\x10.rpc.GameInfoReq\x1a\x10.rpc.GameInfoRep\x12.\n" +
	"\bGameList\x12\x10.rpc.GameListReq\x1a\x10.rpc.GameListRep\x123\n" +
	"\x0eGameListExport\x12\x10.rpc.GameListReq\x1a\r.rpc.GameInfo0\x01B\aZ\x05./rpcb\x06proto3"

var (
	file_dsl_demo_service_proto_rawDescOnce sync.Once
	file_dsl_demo_service_proto_rawDescData []byte
)

func file_dsl_demo_service_proto_rawDescGZIP() []byte {
	file_dsl_demo_service_proto_rawDescOnce.Do(func() {
		file_dsl_demo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dsl_demo_service_proto_rawDesc), len(file_dsl_demo_service_proto_rawDesc)))
	})
	return file_dsl_demo_service_proto_rawDescData
}

var file_dsl_demo_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dsl_demo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_dsl_demo_service_proto_goTypes = []any{
	(SortOrder)(0),                             // 0: rpc.SortOrder
	(SearchOperator)(0),                        // 1: rpc.SearchOperator
	(*FileContext)(nil),                        // 2: rpc.FileContext
	(*PreSignGetRequest)(nil),                  // 3: rpc.PreSignGetRequest
	(*PreSignGetResponse)(nil),                 // 4: rpc.PreSignGetResponse
	(*PreSignPutRequest)(nil),                  // 5: rpc.PreSignPutRequest
	(*PreSignPutResponse)(nil),                 // 6: rpc.PreSignPutResponse
	(*ReportUploadedRequest)(nil),              // 7: rpc.ReportUploadedRequest
	(*ReportUploadedResponse)(nil),             // 8: rpc.ReportUploadedResponse
	(*PreSignSlicingPutRequest)(nil),           // 9: rpc.PreSignSlicingPutRequest
	(*PreSignSlicingPutResponse)(nil),          // 10: rpc.PreSignSlicingPutResponse
	(*GetProgressRate4SlicingPutRequest)(nil),  // 11: rpc.GetProgressRate4SlicingPutRequest
	(*GetProgressRate4SlicingPutResponse)(nil), // 12: rpc.GetProgressRate4SlicingPutResponse
	(*ReportUploadedFilePartsRequest)(nil),     // 13: rpc.ReportUploadedFilePartsRequest
	(*ReportUploadedFilePartsResponse)(nil),    // 14: rpc.ReportUploadedFilePartsResponse
	(*MergeFilePartsRequest)(nil),              // 15: rpc.MergeFilePartsRequest
	(*MergeFilePartsResponse)(nil),             // 16: rpc.MergeFilePartsResponse
	(*RemoveFileRequest)(nil),                  // 17: rpc.RemoveFileRequest
	(*RemoveFileResponse)(nil),                 // 18: rpc.RemoveFileResponse
	(*GetFileInfoByIdRequest)(nil),             // 19: rpc.GetFileInfoByIdRequest
	(*GetFileInfoByIdResponse)(nil),            // 20: rpc.GetFileInfoByIdResponse
	(*Metadata)(nil),                           // 21: rpc.Metadata
	(*SortField)(nil),                          // 22: rpc.SortField
	(*PaginationRequest)(nil),                  // 23: rpc.PaginationRequest
	(*PaginationResponse)(nil),                 // 24: rpc.PaginationResponse
	(*SearchField)(nil),                        // 25: rpc.SearchField
	(*SearchRequest)(nil),                      // 26: rpc.SearchRequest
	(*Request)(nil),                            // 27: rpc.Request
	(*Response)(nil),                           // 28: rpc.Response
	(*GameInfoReq)(nil),                        // 29: rpc.GameInfoReq
	(*GameInfo)(nil),                           // 30: rpc.GameInfo
	(*GameInfoRep)(nil),                        // 31: rpc.GameInfoRep
	(*GameListReq)(nil),                        // 32: rpc.GameListReq
	(*GameListRep)(nil),                        // 33: rpc.GameListRep
	nil,                                        // 34: rpc.GetProgressRate4SlicingPutResponse.PartsEntry
}
var file_dsl_demo_service_proto_depIdxs = []int32{
	2,  // 0: rpc.PreSignGetRequest.file_context:type_name -> rpc.FileContext
	21, // 1: rpc.PreSignGetResponse.meta:type_name -> rpc.Metadata
	2,  // 2: rpc.PreSignPutRequest.file_context:type_name -> rpc.FileContext
	21, // 3: rpc.PreSignPutResponse.meta:type_name -> rpc.Metadata
	2,  // 4: rpc.ReportUploadedRequest.file_context:type_name -> rpc.FileContext
	21, // 5: rpc.ReportUploadedResponse.meta:type_name -> rpc.Metadata
	2,  // 6: rpc.PreSignSlicingPutRequest.file_context:type_name -> rpc.FileContext
	21, // 7: rpc.PreSignSlicingPutResponse.meta:type_name -> rpc.Metadata
	2,  // 8: rpc.GetProgressRate4SlicingPutRequest.file_context:type_name -> rpc.FileContext
	21, // 9: rpc.GetProgressRate4SlicingPutResponse.meta:type_name -> rpc.Metadata
	34, // 10: rpc.GetProgressRate4SlicingPutResponse.parts:type_name -> rpc.GetProgressRate4SlicingPutResponse.PartsEntry
	21, // 11: rpc.ReportUploadedFilePartsResponse.meta:type_name -> rpc.Metadata
	2,  // 12: rpc.MergeFilePartsRequest.file_context:type_name -> rpc.FileContext
	21, // 13: rpc.MergeFilePartsResponse.meta:type_name -> rpc.Metadata
	2,  // 14: rpc.RemoveFileRequest.file_context:type_name -> rpc.FileContext
	21, // 15: rpc.RemoveFileResponse.meta:type_name -> rpc.Metadata
	21, // 16: rpc.GetFileInfoByIdResponse.meta:type_name -> rpc.Metadata
	0,  // 17: rpc.SortField.order:type_name -> rpc.SortOrder
	22, // 18: rpc.PaginationRequest.sort:type_name -> rpc.SortField
	1,  // 19: rpc.SearchField.operator:type_name -> rpc.SearchOperator
	25, // 20: rpc.SearchRequest.search:type_name -> rpc.SearchField
	30, // 21: rpc.GameInfoRep.info:type_name -> rpc.GameInfo
	30, // 22: rpc.GameListRep.list:type_name -> rpc.GameInfo
	3,  // 23: rpc.FileService.PreSignGet:input_type -> rpc.PreSignGetRequest
	5,  // 24: rpc.FileService.PreSignPut:input_type -> rpc.PreSignPutRequest
	7,  // 25: rpc.FileService.ReportUploaded:input_type -> rpc.ReportUploadedRequest
	9,  // 26: rpc.FileService.PreSignSlicingPut:input_type -> rpc.PreSignSlicingPutRequest
	11, // 27: rpc.FileService.GetProgressRate4SlicingPut:input_type -> rpc.GetProgressRate4SlicingPutRequest
	15, // 28: rpc.FileService.MergeFileParts:input_type -> rpc.MergeFilePartsRequest
	17, // 29: rpc.FileService.RemoveFile:input_type -> rpc.RemoveFileRequest
	19, // 30: rpc.FileService.GetFileInfoById:input_type -> rpc.GetFileInfoByIdRequest
	27, // 31: rpc.Rpc_demo.Ping:input_type -> rpc.Request
	29, // 32: rpc.Rpc_demo.FindOne:input_type -> rpc.GameInfoReq
	32, // 33: rpc.Rpc_demo.GameList:input_type -> rpc.GameListReq
	32, // 34: rpc.Rpc_demo.GameListExport:input_type -> rpc.GameListReq
	4,  // 35: rpc.FileService.PreSignGet:output_type -> rpc.PreSignGetResponse
	6,  // 36: rpc.FileService.PreSignPut:output_type -> rpc.PreSignPutResponse
	8,  // 37: rpc.FileService.ReportUploaded:output_type -> rpc.ReportUploadedResponse
	10, // 38: rpc.FileService.PreSignSlicingPut:output_type -> rpc.PreSignSlicingPutResponse
	12, // 39: rpc.FileService.GetProgressRate4SlicingPut:output_type -> rpc.GetProgressRate4SlicingPutResponse
	16, // 40: rpc.FileService.MergeFileParts:output_type -> rpc.MergeFilePartsResponse
	18, // 41: rpc.FileService.RemoveFile:output_type -> rpc.RemoveFileResponse
	20, // 42: rpc.FileService.GetFileInfoById:output_type -> rpc.GetFileInfoByIdResponse
	28, // 43: rpc.Rpc_demo.Ping:output_type -> rpc.Response
	31, // 44: rpc.Rpc_demo.FindOne:output_type -> rpc.GameInfoRep
	33, // 45: rpc.Rpc_demo.GameList:output_type -> rpc.GameListRep
	30, // 46: rpc.Rpc_demo.GameListExport:output_type -> rpc.GameInfo
	35, // [35:47] is the sub-list for method output_type
	23, // [23:35] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_dsl_demo_service_proto_init() }
func file_dsl_demo_service_proto_init() {
	if File_dsl_demo_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dsl_demo_service_proto_rawDesc), len(file_dsl_demo_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dsl_demo_service_proto_goTypes,
		DependencyIndexes: file_dsl_demo_service_proto_depIdxs,
		EnumInfos:         file_dsl_demo_service_proto_enumTypes,
		MessageInfos:      file_dsl_demo_service_proto_msgTypes,
	}.Build()
	File_dsl_demo_service_proto = out.File
	file_dsl_demo_service_proto_goTypes = nil
	file_dsl_demo_service_proto_depIdxs = nil
}
